# Generated by Django 5.1.2 on 2024-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='news-images/')),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.TextField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='client-documents/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='client-documents/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='client-documents/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image1',
            field=models.ImageField(blank=True, upload_to='client-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image2',
            field=models.ImageField(blank=True, upload_to='client-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image3',
            field=models.ImageField(blank=True, upload_to='client-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image4',
            field=models.ImageField(blank=True, upload_to='client-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image5',
            field=models.ImageField(blank=True, upload_to='client-images/'),
        ),
    ]
