# Generated by Django 5.1.2 on 2024-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_news_alter_request_file1_alter_request_file2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news-images/'),
        ),
    ]
