# Generated by Django 5.1.2 on 2024-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='client-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image1',
            field=models.ImageField(blank=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image2',
            field=models.ImageField(blank=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image3',
            field=models.ImageField(blank=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image4',
            field=models.ImageField(blank=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image5',
            field=models.ImageField(blank=True, upload_to='request-images/'),
        ),
    ]
