# Generated by Django 5.1.2 on 2024-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_profile_name_client_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
