# Generated by Django 5.1.2 on 2024-10-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password1',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='password2',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='postalCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
