# Generated by Django 5.1.2 on 2024-11-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_request_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.RemoveField(
            model_name='request',
            name='created',
        ),
    ]
