# Generated by Django 5.1.2 on 2024-11-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_request_options_remove_request_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Request2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.ImageField(blank=True, upload_to='request-images/')),
                ('image2', models.ImageField(blank=True, upload_to='request-images/')),
                ('image3', models.ImageField(blank=True, upload_to='request-images/')),
                ('image4', models.ImageField(blank=True, upload_to='request-images/')),
                ('image5', models.ImageField(blank=True, upload_to='request-images/')),
                ('file1', models.FileField(blank=True, null=True, upload_to='client-documents/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='client-documents/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='client-documents/')),
                ('material', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('Classic', 'Classic'), ('Modern', 'Modern'), ('Different', 'Different')], default='Classic', max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('urgent', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('mailbox_send', models.BooleanField(default=False)),
                ('relaypoint_send', models.BooleanField(default=False)),
                ('deadline', models.IntegerField()),
                ('accepted_manufacturer_id', models.IntegerField(blank=True, null=True)),
                ('completed_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_date', models.DateField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
