# Generated by Django 5.1.2 on 2024-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_request_options_request_created_request2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request2',
            name='deadline',
        ),
        migrations.AddField(
            model_name='request2',
            name='expire',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
