# Generated by Django 5.1.2 on 2024-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_request_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='request2',
            name='expire',
        ),
        migrations.AddField(
            model_name='request',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request2',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
