# Generated by Django 5.1.2 on 2024-11-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_remove_request_expire_remove_request2_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request2',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request2',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request2',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request2',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='request-images/'),
        ),
        migrations.AlterField(
            model_name='request2',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='request-images/'),
        ),
    ]
