# Generated by Django 5.1.2 on 2024-11-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thierry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RenameModel(
            old_name='FAQ',
            new_name='ClientFAQ',
        ),
    ]
