# Generated by Django 5.1.2 on 2024-11-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thierry', '0002_manfaq_rename_faq_clientfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
