# Generated by Django 5.1.2 on 2024-11-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thierry', '0004_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ('-created',), 'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
    ]
