# Generated by Django 5.1.2 on 2024-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_remove_rating_client_rating_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='profile_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='manuf-images/'),
        ),
    ]
