# Generated by Django 5.1.2 on 2024-11-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_remove_request_expire_remove_request2_expire_and_more'),
        ('manufacturer', '0006_manufacturer_address_manufacturer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.request2'),
        ),
    ]
