# Generated by Django 5.1.2 on 2024-10-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_news_alter_request_file1_alter_request_file2_and_more'),
        ('directs', '0001_initial'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmessage',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='clientmessage',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='clientmessage',
            old_name='reciepient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='manufacturermessage',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='manufacturermessage',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='manufacturermessage',
            old_name='reciepient',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='clientmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manufacturermessage',
            name='user',
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user_cmsg', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='manufacturer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_user_cmsg', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='manufacturermessage',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user_mmsg', to='client.client'),
        ),
        migrations.AddField(
            model_name='manufacturermessage',
            name='manufacturer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_user_mmsg', to='manufacturer.manufacturer'),
        ),
    ]
