# Generated by Django 5.1.2 on 2024-10-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0002_rename_date_clientmessage_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmessage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='manufacturermessage',
            options={'ordering': ('-created',)},
        ),
    ]
